networks:
  kafka-net:
    ipam:
      config:
        - subnet: 172.18.0.0/16
services:
  kafka1:
    container_name: kafka1
    image: erkansirin78/kafka:3.8.0
    ports:
        - "9092:9092"
    networks:
      kafka-net:
        ipv4_address: 172.18.0.11
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/
  kafka2:
    container_name: kafka2
    image: erkansirin78/kafka:3.8.0
    ports:
        - "9292:9092"
    networks:
      kafka-net:
        ipv4_address: 172.18.0.12
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/
  kafka3:
    container_name: kafka3
    image: erkansirin78/kafka:3.8.0
    ports:
        - "9392:9092"
    networks:
      kafka-net:
        ipv4_address: 172.18.0.13
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/
  schema_registry:
    container_name: schema_registry
    hostname: schema_registry
    image: confluentinc/cp-schema-registry:7.7.1
    depends_on:
      - kafka1
      - kafka2
    ports:
        - "8085:8085"
    environment:
      - "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka1:9092"
      - "SCHEMA_REGISTRY_HOST_NAME=schema_registry"
      - "SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085"
    networks:
      kafka-net:
        ipv4_address: 172.18.0.14